- type: job
  id: InteQVanguardLeader
  name: job-name-inteq-vanguard-leader
  description: job-description-inteq-vanguard-leader
  playTimeTracker: InteQVanguardLeader
  setPreference: false
  icon: "JobIconInteQ"
  supervisors: job-supervisors-hire
  canBeAntag: false
  access:
  - InteQVanguard
  - InteQVanguardLeader
  - Maintenance
  whitelisted: true # Europa Edit

- type: job
  id: InteQVanguard
  name: job-name-inteq-vanguard
  description: job-description-inteq-vanguard
  playTimeTracker: InteQVanguard
  setPreference: false
  icon: "JobIconInteQ"
  supervisors: job-supervisors-hire
  canBeAntag: false
  access:
  - InteQVanguard
  - Maintenance
  whitelisted: true # Europa Edit
